# Generated by Django 2.2.2 on 2020-01-09 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_EPIC_CAPABILITY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cepic_key', models.CharField(max_length=50)),
                ('Cepic_desc', models.TextField()),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(on_delete='models.SET_NULL', to='account.AR_organization')),
                ('PROJECT_ID', models.ManyToManyField(blank=True, default='', to='manage_product.AR_product')),
                ('created_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='create_by_epic', to='account.Ar_user')),
                ('update_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='update_by_epic', to='account.Ar_user')),
            ],
        ),
    ]
