# Generated by Django 2.2.2 on 2020-01-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArUserStoryPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_Key', models.CharField(default='Point_Key dvfdvf sdcdfc', max_length=50)),
                ('Point_Description', models.TextField(default='Set Description')),
                ('Point_score', models.BigIntegerField(default=10)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(default='', on_delete='models.SET_NULL', related_name='UserCreateBy', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(default='', on_delete='models.SET_NULL', related_name='UserUpdateBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
