# Generated by Django 2.2.2 on 2020-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_points', '0002_auto_20200109_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aruserstorypoints',
            name='Point_Key',
            field=models.CharField(default='Point_Key', max_length=50, unique=True),
        ),
    ]
