# Generated by Django 2.2.2 on 2020-01-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200114_0653'),
        ('user_story_points', '0003_auto_20200115_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserstorypoints',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='account.AR_organization'),
        ),
    ]
