# Generated by Django 2.2.2 on 2020-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_points', '0004_aruserstorypoints_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aruserstorypoints',
            name='create_by',
            field=models.ForeignKey(default='', on_delete='models.SET_NULL', related_name='UserCreateBy', to='account.Ar_user'),
        ),
        migrations.AlterField(
            model_name='aruserstorypoints',
            name='update_by',
            field=models.ForeignKey(default='', on_delete='models.SET_NULL', related_name='UserUpdateBy', to='account.Ar_user'),
        ),
    ]
