# Generated by Django 2.2.2 on 2020-02-04 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=50, unique=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_url', models.URLField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('subscription_level', models.CharField(blank=True, max_length=50)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2personsorganization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ar_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default=None, max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zip', models.IntegerField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.BigIntegerField(blank=True, default='')),
                ('backup_email', models.EmailField(blank=True, default='', max_length=50)),
                ('user_type', models.CharField(default='Root', max_length=50)),
                ('subscription_level', models.CharField(default='Free trial', max_length=50)),
                ('active_user', models.IntegerField(default=0)),
                ('user_to_invite', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('login_status', models.BooleanField(default=False)),
                ('activate_status', models.BooleanField(default=False)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('org_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
            ],
        ),
        migrations.CreateModel(
            name='ArHelpContect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_name', models.CharField(max_length=50)),
                ('Page_slug', models.CharField(blank=True, help_text='Copy URL after the http://203.190.153.20/ and past', max_length=250, null=True, unique=True)),
                ('Topic', models.CharField(max_length=50)),
                ('Description', models.TextField(default='Description')),
                ('Information', models.TextField(default='Information.')),
                ('Linke_1', models.URLField(blank=True, default='http://203.190.153.20/', null=True)),
                ('Linke_2', models.URLField(blank=True, default='http://203.190.153.20/', null=True)),
                ('Linke_3', models.URLField(blank=True, default='http://203.190.153.20/', null=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ArUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(blank=True, max_length=50)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_by_organization', to='account.AR_organization')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_userprofile', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArUserStoryScoringPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_for', models.CharField(max_length=50)),
                ('Score_key', models.CharField(max_length=50)),
                ('Keyword', models.TextField()),
                ('Score_one', models.IntegerField(default=0)),
                ('Score_two', models.IntegerField(default=0)),
                ('Score_three', models.IntegerField(default=0)),
                ('Last_Update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50)),
                ('notification_key', models.CharField(max_length=50)),
                ('notification_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='csvFilesUplodaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(upload_to='csvfileuplodaded/')),
                ('csvUseFor', models.CharField(max_length=50)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.AR_organization')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_csvFilesUplodaded', to='account.Ar_user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_csvFilesUplodaded', to='account.Ar_user')),
            ],
        ),
        migrations.CreateModel(
            name='ArUserProfilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activites', models.CharField(max_length=80)),
                ('editor', models.BooleanField(default=False)),
                ('viewer', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilepermission_by_organization', to='account.AR_organization')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_userprofilepermission', to=settings.AUTH_USER_MODEL)),
                ('profile_key', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofilepermission_by_userprofile', to='account.ArUserProfile')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_userprofilepermission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArShowcolumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_name', models.CharField(max_length=50)),
                ('columnName', models.TextField()),
                ('ORG', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Ar_user')),
            ],
        ),
        migrations.AddField(
            model_name='ar_user',
            name='profile_permission',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='account.ArUserProfile'),
        ),
        migrations.AddField(
            model_name='ar_user',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AR_organization_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(max_length=50)),
                ('status_desc', models.TextField(blank=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2personsstatuStatus', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendsStatus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ar_organization',
            name='organization_status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization_status'),
        ),
        migrations.AddField(
            model_name='ar_organization',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendsorganization', to=settings.AUTH_USER_MODEL),
        ),
    ]
