# Generated by Django 2.2.2 on 2020-01-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user',
            name='org_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='arshowcolumns',
            name='ORG',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='aruserprofile',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='userprofile_by_organization', to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='aruserprofilepermission',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='userprofilepermission_by_organization', to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='aruserprofilepermission',
            name='profile_key',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='userprofilepermission_by_userprofile', to='account.ArUserProfile'),
        ),
        migrations.AlterField(
            model_name='csvfilesuplodaded',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.AR_organization'),
        ),
    ]
