# Generated by Django 2.2.2 on 2020-02-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_organization',
            options={'verbose_name_plural': 'Ar organization'},
        ),
        migrations.AlterModelOptions(
            name='ar_organization_status',
            options={'verbose_name_plural': 'Ar organization status'},
        ),
        migrations.AlterModelOptions(
            name='ar_user',
            options={'verbose_name_plural': 'Ar user'},
        ),
        migrations.AlterModelOptions(
            name='arhelpcontect',
            options={'verbose_name_plural': 'Ar help contect'},
        ),
        migrations.AlterModelOptions(
            name='arshowcolumns',
            options={'verbose_name_plural': 'Ar show columns'},
        ),
        migrations.AlterModelOptions(
            name='aruserprofile',
            options={'verbose_name_plural': 'Ar user profile'},
        ),
        migrations.AlterModelOptions(
            name='aruserprofilepermission',
            options={'verbose_name_plural': 'Ar user profile permission'},
        ),
        migrations.AlterModelOptions(
            name='aruserstoryscoringpoints',
            options={'verbose_name_plural': 'Ar user story scoring points'},
        ),
        migrations.AlterModelOptions(
            name='csvfilesuplodaded',
            options={'verbose_name_plural': 'CSV files uploaded'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification'},
        ),
    ]
