# Generated by Django 2.2.2 on 2020-01-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200114_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user',
            name='status',
            field=models.CharField(default='Not Active', max_length=50),
        ),
    ]
