# Generated by Django 2.2.2 on 2020-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200205_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_user',
            name='terms_accept',
            field=models.BooleanField(default=True),
        ),
    ]
