# Generated by Django 2.2.2 on 2020-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200116_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50)),
                ('notification_key', models.CharField(max_length=50)),
                ('notification_desc', models.TextField()),
            ],
        ),
    ]
