# Generated by Django 2.2.2 on 2020-01-23 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArUserStoryScoringPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_key', models.CharField(max_length=50)),
                ('Score_type', models.CharField(max_length=50)),
                ('Keyword', models.TextField()),
                ('Score', models.IntegerField()),
                ('Last_Update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
