# Generated by Django 2.2.2 on 2020-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_aruserstoryscoringpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aruserstoryscoringpoints',
            name='Score',
        ),
        migrations.AddField(
            model_name='aruserstoryscoringpoints',
            name='Score_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aruserstoryscoringpoints',
            name='Score_three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aruserstoryscoringpoints',
            name='Score_two',
            field=models.IntegerField(default=0),
        ),
    ]
