# Generated by Django 2.2.2 on 2020-01-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200123_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aruserstoryscoringpoints',
            old_name='Score_type',
            new_name='Score_for',
        ),
    ]
