# Generated by Django 2.2.2 on 2020-01-27 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200123_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArHelpContect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_name', models.CharField(max_length=50)),
                ('Page_slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('Topic', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Information', models.TextField()),
                ('Linke_1', models.URLField(blank=True, null=True)),
                ('Linke_2', models.URLField(blank=True, null=True)),
                ('Linke_3', models.URLField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
