# Generated by Django 2.2.2 on 2020-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_arhelpcontect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Description',
            field=models.TextField(default='Dashboard Page'),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Information',
            field=models.TextField(default='This Page Provides All Details.'),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Linke_1',
            field=models.URLField(blank=True, default='http://203.190.153.20/', null=True),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Linke_2',
            field=models.URLField(blank=True, default='http://203.190.153.20/', null=True),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Linke_3',
            field=models.URLField(blank=True, default='http://203.190.153.20/', null=True),
        ),
    ]
