# Generated by Django 2.2.2 on 2020-01-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Information',
            field=models.TextField(default='Information.'),
        ),
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Page_name',
            field=models.CharField(max_length=50),
        ),
    ]
