# Generated by Django 2.2.2 on 2020-02-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200127_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arhelpcontect',
            name='Page_slug',
            field=models.CharField(blank=True, help_text='Copy URL after the http://203.190.153.20/ and past', max_length=250, null=True, unique=True),
        ),
    ]
