# Generated by Django 2.2.2 on 2020-02-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_backlog',
            options={'verbose_name_plural': 'Ar backlog'},
        ),
        migrations.AlterModelOptions(
            name='ar_backlog_status',
            options={'verbose_name_plural': 'Ar backlog status'},
        ),
    ]
