# Generated by Django 2.2.2 on 2020-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_backlog',
            name='BL_STATUS',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='manage_backlogs.AR_BACKLOG_STATUS'),
        ),
        migrations.AlterField(
            model_name='ar_backlog',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='ar_backlog',
            name='product_parent',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='manage_product.AR_product'),
        ),
        migrations.AlterField(
            model_name='ar_backlog',
            name='team_list',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='manage_product.AR_team'),
        ),
    ]
