# Generated by Django 2.2.2 on 2020-01-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0003_auto_20200115_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_backlog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
