# Generated by Django 2.2.2 on 2020-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0005_auto_20200125_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_backlog',
            name='product_parent',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='backlog_by_product', to='manage_product.AR_product'),
        ),
    ]
