# Generated by Django 2.2.2 on 2020-01-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0006_auto_20200128_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_backlog',
            name='children_us_list',
        ),
    ]
