# Generated by Django 2.2.2 on 2020-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0005_remove_ar_product_children_backlog_list'),
        ('manage_backlogs', '0007_remove_ar_backlog_children_us_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_backlog',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='account.Ar_user'),
        ),
        migrations.RemoveField(
            model_name='ar_backlog',
            name='team_list',
        ),
        migrations.AddField(
            model_name='ar_backlog',
            name='team_list',
            field=models.ManyToManyField(blank=True, related_name='backlog_team', to='manage_product.AR_team'),
        ),
    ]
