# Generated by Django 2.2.2 on 2020-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_role', '0002_arrole_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrole',
            name='use',
            field=models.TextField(blank=True, default=''),
        ),
    ]
