# Generated by Django 2.2.2 on 2020-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='All_member',
            field=models.BooleanField(blank=True, default=False, help_text='View for All Member.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Description',
            field=models.TextField(blank=True, help_text='Description about package.'),
        ),
    ]
