# Generated by Django 2.2.2 on 2020-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200314_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Undefine_price',
            field=models.BooleanField(blank=True, default=False, help_text='Q3 2020'),
        ),
    ]
