# Generated by Django 2.2.2 on 2020-03-14 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('subscription', '0003_auto_20200314_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_status', models.BooleanField(blank=True, default=False)),
                ('Description', models.TextField(blank=True, help_text='Description about request.')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Organization', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='Organization_MembershipRequest', to='account.AR_organization')),
                ('Request_for', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='Request_for_MembershipRequest', to='subscription.Subscription')),
                ('Request_from', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='Request_from_MembershipRequest', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Membership Request',
            },
        ),
    ]
