# Generated by Django 2.2.2 on 2020-02-04 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_story_view', '0001_initial'),
        ('account', '0001_initial'),
        ('manage_epic_capability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_FEATURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_key', models.CharField(blank=True, default='', max_length=50)),
                ('Feature_desc', models.TextField(blank=True, default='')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('CE_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_epic_capability.AR_EPIC_CAPABILITY')),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('User_story', models.ManyToManyField(blank=True, default='', to='user_story_view.AR_USER_STORY')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_feature', to='account.Ar_user')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_feature', to='account.Ar_user')),
            ],
        ),
    ]
