# Generated by Django 2.2.2 on 2020-02-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_features', '0002_auto_20200205_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='CE_ID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_from_feature', to='manage_epic_capability.AR_EPIC_CAPABILITY'),
        ),
    ]
