# Generated by Django 2.2.2 on 2020-02-04 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('feedback_nature', models.TextField(blank=True)),
                ('feedback_information', models.TextField()),
                ('attachments', models.FileField(upload_to='feedback/')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_feedback', to='account.Ar_user')),
            ],
        ),
    ]
