# Generated by Django 2.2.2 on 2020-01-09 14:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('feedback_nature', models.TextField(blank=True)),
                ('feedback_information', models.TextField()),
                ('attachments', models.FileField(upload_to='feedback/')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='created_by_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
