# Generated by Django 2.2.2 on 2020-03-13 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArSendFeedbackEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_id_for_sent', to='feedback.ArFeedback')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id_for_sent', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar send feedback email',
            },
        ),
    ]
