# Generated by Django 2.2.2 on 2020-01-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arfeedback',
            name='created_by',
            field=models.ForeignKey(on_delete='models.SET_NULL', related_name='created_by_feedback', to='account.Ar_user'),
        ),
    ]
