# Generated by Django 2.2.2 on 2020-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_arsendfeedbackemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsendfeedbackemail',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
