# Generated by Django 2.2.2 on 2020-03-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('manage_backlogs', '0001_initial'),
        ('user_story_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_US_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(blank=True, max_length=50, unique=True)),
                ('status_desc', models.TextField(blank=True)),
                ('status_shortcode', models.CharField(blank=True, max_length=50, unique=True)),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('create_by', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='create_by_us_status', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='update_by_us_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ar user story status',
            },
        ),
        migrations.CreateModel(
            name='AR_US_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(blank=True, max_length=50, unique=True)),
                ('type_desc', models.TextField(blank=True)),
                ('type_short_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='create_by_us_type', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='update_by_us_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ar user story type',
            },
        ),
        migrations.CreateModel(
            name='AR_USER_STORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('story_tri_part_text', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('ac_readability_score', models.BigIntegerField(blank=True)),
                ('conversation', models.TextField(blank=True)),
                ('convo_readability_score', models.BigIntegerField(blank=True)),
                ('attachments', models.FileField(blank=True, default='None', null=True, upload_to='attachments/')),
                ('autoscoring_on', models.BooleanField(blank=True, default=False)),
                ('archive_indicator', models.BooleanField(blank=True, default=False)),
                ('readiness_quality_score', models.BigIntegerField(blank=True)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.AR_organization')),
                ('UST_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_story_view.AR_US_TYPE')),
                ('ar_user', models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='ar_user', to='account.Ar_user')),
                ('backlog_parent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='story_by_backlog', to='manage_backlogs.AR_BACKLOG')),
                ('created_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='create_by_user_story', to='account.Ar_user')),
                ('owner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Ar_user')),
                ('story_points', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_points', to='user_story_points.ArUserStoryPoints')),
                ('updated_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='update_by_user_story', to='account.Ar_user')),
                ('user_story_status', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_story_view.AR_US_STATUS')),
            ],
            options={
                'verbose_name_plural': 'Ar user story',
            },
        ),
    ]
