# Generated by Django 2.2.2 on 2020-01-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='ORG_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='UST_ID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_story_view.AR_US_TYPE'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='ar_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.Ar_user'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='backlog_parent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manage_backlogs.AR_BACKLOG'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='story_points',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_points', to='manage_epic_capability.AR_EPIC_CAPABILITY'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='user_story_status',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_story_view.AR_US_STATUS'),
        ),
    ]
