# Generated by Django 2.2.2 on 2020-02-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_us_status',
            options={'verbose_name_plural': 'Ar user story status'},
        ),
    ]
