# Generated by Django 2.2.2 on 2020-01-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0002_auto_20200114_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='story_points',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_points', to='user_story_points.ArUserStoryPoints'),
        ),
    ]
