# Generated by Django 2.2.2 on 2020-02-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0002_auto_20200205_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_us_type',
            options={'verbose_name_plural': 'Ar user story type'},
        ),
        migrations.AlterModelOptions(
            name='ar_user_story',
            options={'verbose_name_plural': 'Ar user story'},
        ),
    ]
