# Generated by Django 2.2.2 on 2020-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0003_auto_20200114_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='ar_user',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='ar_user', to='account.Ar_user'),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', related_name='owner', to='account.Ar_user'),
        ),
    ]
