# Generated by Django 2.2.2 on 2020-01-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0004_auto_20200124_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='backlog_parent',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='story_by_backlog', to='manage_backlogs.AR_BACKLOG'),
        ),
    ]
