# Generated by Django 2.2.2 on 2020-02-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0005_auto_20200207_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='readiness_quality_score',
            field=models.FloatField(blank=True),
        ),
    ]
