# Generated by Django 2.2.2 on 2020-02-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0006_auto_20200208_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user_story',
            name='ac_readability_score',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='convo_readability_score',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='readiness_quality_score',
            field=models.BigIntegerField(blank=True),
        ),
    ]
