# Generated by Django 2.2.2 on 2020-03-04 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0008_auto_20200229_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='create_by_us_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='update_by_us_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='create_by_us_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='models.SET_NULL', related_name='update_by_us_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
