# Generated by Django 2.2.2 on 2020-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpuser', '0003_auto_20200225_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms_manage',
            name='keyword',
            field=models.SlugField(blank=True),
        ),
    ]
