# Generated by Django 2.2.2 on 2020-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_product',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete='models.SET_NULL', to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='ar_team',
            name='ORG_id',
            field=models.ForeignKey(default='', null=True, on_delete='models.CASCADE', to='account.AR_organization'),
        ),
    ]
