# Generated by Django 2.2.2 on 2020-02-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_product',
            options={'verbose_name_plural': 'Ar product'},
        ),
        migrations.AlterModelOptions(
            name='ar_team',
            options={'verbose_name_plural': 'Ar team'},
        ),
    ]
