# Generated by Django 2.2.2 on 2020-01-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0003_auto_20200122_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_product',
            name='Children_backlog_list',
        ),
        migrations.AddField(
            model_name='ar_product',
            name='Children_backlog_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
