# Generated by Django 2.2.2 on 2020-01-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0004_auto_20200123_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_product',
            name='Children_backlog_list',
        ),
    ]
