# Generated by Django 2.2.4 on 2020-01-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aruserstorypoints',
            old_name='epic',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='ORG_ID',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='extra_extra_extra_large',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='extra_extra_large',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='extra_large',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='large',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='small',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='smallish',
        ),
        migrations.RemoveField(
            model_name='aruserstorypoints',
            name='very_small',
        ),
        migrations.AddField(
            model_name='aruserstorypoints',
            name='point_desc',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
