# Generated by Django 2.2.2 on 2020-03-13 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dommy_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='implode_data/')),
                ('file_name', models.CharField(max_length=50)),
                ('file_data', models.TextField(max_length=50)),
                ('upload_status', models.BooleanField(default=False)),
                ('error_log', models.FileField(blank=True, default='None', null=True, upload_to='implode_data/error_log')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Dommy data',
            },
        ),
        migrations.CreateModel(
            name='export_data_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50)),
                ('files_name', models.TextField(blank=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Export data info',
            },
        ),
        migrations.CreateModel(
            name='import_files_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='implode_data/')),
                ('file_name', models.CharField(max_length=50)),
                ('file_data', models.TextField()),
                ('upload_status', models.BooleanField(default=False)),
                ('error_log', models.FileField(blank=True, default='None', null=True, upload_to='implode_data/error_log')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=0)),
                ('dommy_set', models.IntegerField(default=0)),
                ('ORG_ID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_import_data', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Import files data',
            },
        ),
    ]
