# Generated by Django 2.2.2 on 2020-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0002_file_info_import_files_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_files_data',
            old_name='files_name',
            new_name='file_data',
        ),
        migrations.AddField(
            model_name='import_files_data',
            name='error_log',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_files_data',
            name='file_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_files_data',
            name='files',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='file_info',
        ),
    ]
