# Generated by Django 2.2.2 on 2020-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0003_auto_20200214_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_files_data',
            name='error_log',
            field=models.FileField(blank=True, default='None', null=True, upload_to='implode_data/error_log'),
        ),
        migrations.AlterField(
            model_name='import_files_data',
            name='file_data',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='import_files_data',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='import_files_data',
            name='files',
            field=models.FileField(upload_to='implode_data/'),
        ),
    ]
