# Generated by Django 2.2.2 on 2020-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0004_auto_20200214_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_files_data',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
    ]
