# Generated by Django 2.2.2 on 2020-02-21 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0006_import_files_data_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='dommy_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='implode_data/')),
                ('file_name', models.CharField(max_length=50)),
                ('file_data', models.TextField(max_length=50)),
                ('upload_status', models.BooleanField(default=False)),
                ('error_log', models.FileField(blank=True, default='None', null=True, upload_to='implode_data/error_log')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
