# Generated by Django 2.2.2 on 2020-02-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0007_dommy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dommy_data',
            options={'verbose_name_plural': 'Dommy data'},
        ),
        migrations.AlterModelOptions(
            name='export_data_info',
            options={'verbose_name_plural': 'Export data info'},
        ),
        migrations.AlterModelOptions(
            name='import_files_data',
            options={'verbose_name_plural': 'Import files data'},
        ),
        migrations.AddField(
            model_name='import_files_data',
            name='dommy_set',
            field=models.IntegerField(default=0),
        ),
    ]
