# Generated by Django 2.2.2 on 2020-02-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0009_auto_20200229_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_files_data',
            name='ORG_ID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization'),
        ),
    ]
