# Generated by Django 2.2.2 on 2020-02-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0010_auto_20200229_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_files_data',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_import_data', to='account.Ar_user'),
        ),
    ]
