# Generated by Django 2.2.2 on 2020-03-13 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('manage_backlogs', '0001_initial'),
        ('manage_product', '0001_initial'),
        ('user_story_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArIterations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IterationName', models.CharField(blank=True, max_length=50)),
                ('IterationId', models.TextField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.TextField()),
                ('IterationScore', models.FloatField(blank=True, null=True)),
                ('IterationSize', models.IntegerField(blank=True, null=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Backlog', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlogArIterations', to='manage_backlogs.AR_BACKLOG')),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamArIterations', to='account.AR_organization')),
                ('Product', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productArIterations', to='manage_product.AR_product')),
                ('Team', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamArIterations', to='manage_product.AR_team')),
                ('UserStory', models.ManyToManyField(blank=True, default='', related_name='userstoryArIterations', to='user_story_view.AR_USER_STORY')),
                ('create_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='create_by_iterations', to='account.Ar_user')),
                ('owner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Ar_user')),
                ('update_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='update_by_iterations', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar iterations',
            },
        ),
    ]
