# Generated by Django 2.2.2 on 2020-01-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='Backlog',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlogArIterations', to='manage_backlogs.AR_BACKLOG'),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='ORG_ID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamArIterations', to='account.AR_organization'),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='Product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productArIterations', to='manage_product.AR_product'),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='Team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamArIterations', to='manage_product.AR_team'),
        ),
    ]
