# Generated by Django 2.2.2 on 2020-02-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='EndDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='StartDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
