# Generated by Django 2.2.2 on 2020-02-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0003_auto_20200204_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='EndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
