# Generated by Django 2.2.2 on 2020-02-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0004_auto_20200204_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ariterations',
            options={'verbose_name_plural': 'Ar iterations'},
        ),
    ]
