# Generated by Django 2.2.2 on 2020-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0005_auto_20200205_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='IterationScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ariterations',
            name='IterationSize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
