# Generated by Django 2.2.2 on 2020-02-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0006_auto_20200205_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Ar_user'),
        ),
    ]
