# Generated by Django 2.2.2 on 2020-02-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0007_auto_20200205_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
