# Generated by Django 2.2.2 on 2020-02-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_iterations', '0009_auto_20200205_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariterations',
            name='IterationScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
